spring.application.name=LogiTrack
spring.datasource.url=jdbc:mysql://localhost:3306/LogiTrack_1?createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.mvc.servlet.path=/api

jwt.secret=logitrack-secret-key-must-be-at-least-256-bits-long-for-HS256
